### ISSUE TITLE
Roadmap to Juntagrico 2.0

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#528]
Juntagricos community is growing and demands are rising. In order to meet the functionality and customization demands, Juntagrico should become easier to modify in the Django project (without adding settings) and it should be easier to write AddOns.

I'll list here what I think we should do to achieve this.

- [ ] Use custom querysets/managers (see poc). This helps to decouple the models and make it easier to extend them.
- [ ] Use Template overrides (see issue)
   - [ ] Finish the Text overrides.
- [ ] Make the sign-up process easier to extend.
- [ ] Move the delivery feature and shares(!) to separate AddOns. Doing so will prove the extendability and show more todos on the way.

While modifying this we can also clean up some stuff for a 2.0 release:

- [ ] Use the AppConfig (in Juntagrico and AddOns) and use it to replace the addon config to register Name and version of AddOns.
   - [ ] Rename the Config class to JuntagricoSettings, because the name config conflicts with the AppConfig, which does something else.

More points will probably follow.

**Comment by pascalfree** [comment]
## Better Test Setup

- [x] Make test setups faster and resuable

Implemented by:
- https://github.com/juntagrico/juntagrico/commit/51a68e93a2de03851fee979085ceb3a508a5411e
- https://github.com/juntagrico/juntagrico/commit/aba89f29647f1148090e5bcf7b7c2236347b274b
