### ISSUE TITLE
Model Validation & Database Consistency

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#531]
I've looked a bit into the topic of database consistency, i.e. that the data in the data base "makes sense" and respects certain requirements.
These are my notes and some general and more detailed thoughts.

# Theory

## Levels of Validation

There are 2 levels of validation in Django and kind of an additional one in between:

1. Database [Constraints](https://docs.djangoproject.com/en/4.0/ref/models/constraints/): These are enforced on the database itself and when violated the database will complain and saving an objects will fail. Some of these are database specific. The most common one is the unique constraint. These checks are always performed, no matter how the data is entered to the database.
2. Model validation: This can be achieved in Django by adding a "presave" or "m2m_change" hook to a model that then checks if it is allowed to save the modified object with the current information. These checks are performed whenever a model object is saved.
3. [Form validation](https://docs.djangoproject.com/en/4.0/ref/forms/validation/): These validations check the content of a form. This is only checked for inputs via form and must be adjusted to the form.

## Issues with Validation

Ideally all changes on the database that lead to an "incorrect" state would be prevented and the user would recieve a meaningful message telling them why things failed. Django does a lot to help reaching that goal. However, depending on the validation this is hard to achieve.
The issues show up, when validation requires checking the object that sould be saved against other related objects. Examples of these can be found below. There is no issue if only one object is changed at once and it can be checked agains the other objects in the database. If however two objects are changed at the same time (e.g. via Inlines in the django admin) applying both changes might be consistent but the django admin saves the objects sequentially, and the change of the first object only, might lead to an inconsistent state in the database. Example: Edit a subscription with 2 memberships, swap the members in those 2 memberships in the inline and save. It will fail, because saving the first membership would result in a duplicate key "member" (as the second membership is still stored in the db with the same member at that stage).
Result: If we add all the required constraints or model validations, it gets harder to edit the model in the django admin. In the end each related object must be modified one by one.
This is an issue of Django itself and might be fixed in the future.

## Idea

In the best case the data in the database would be structured in a way, that it can't be inconsistent, i.e. that complex consistency checks would not be necessary.
Often the need for checks indicates that an information in the database is redundant in some form.
In the following I'm going through the checks that we do in juntagrico to see if they could be solved differently.

# Checks in Juntagrico

Here is an overview of the constraints, model validations and form validations we currently have on Juntagrico. Not mentioning the unique constraints here.

### check that members in subscription have sufficient shares (in part order form)

Similarly this is checked, when leaving a subscription (i.e. if leaving is possible at all) or cancelling shares. This might be the most complex check in the code. I can't think of a way to simplify that.

### check that at least one subscription was selected (in part order form)

Only for the form. Does not affect db. If nothing is selected nothing would be created.

### check that subscription has at least one part

- [ ] Probably redundant because it's checked again in the model validation

### Prevent reactivation of subscription

- [ ] Does not affect database consistency. Evaluate if this check is still needed. What are the consequences of reactivation?

### Check date order of subscription

That's an easy one and causes no issues

### Check that memberships and parts start and end within subscription start and end (when saving the subscription)

- [ ] This one causes some issues in the django admin and forces the user to first change dates on the parts and memberships and then on the subscription. The user will get a hint, what to do in this case. Suggested solution: #366

### Check that primary memer has an active membership on the subscription

- [ ] See #529

### check that subscription has at least one part

Again, but differently than form validation
- [ ] Couldn't we allow "empty" subscriptions? 

### When subscription is activated all waiting memberships are activated as well: Check that members have no unterminated other membership that would prevent the activation of this one.

Possibly redundant, as this is checked again on saving the membership
- [ ] instead this member could be kept as "waiting" or other membership could be left automatically.

### Check date order of subscription membership

easy

### Check that membership starts and ends within subscription start and end (when saving the membership)

- [ ] See also: #366. If "empty" subscriptions would be allowed, this check would not be needed.

### Check that the memberships of a member do not overlap

- [ ] In situations with extra subscriptions it becomes more likely, that a member would want to join 2 subscriptions at the same time. On issue arising from that would be to count the assignments. This could be solved with https://github.com/juntagrico/juntagrico/issues/521#issuecomment-1059850238 .
Secondly the share counting would be even more complex.
If instead we want to keep this constraint, the membership should only have a join_date. Leave dates would be implicit (end of subscription) or if leaving before a new membership would be created with where join_date is the date that this subscription is left and subscription field is empty to indicate that the member moves to no subscription on that date.

### Check date order of subscription part

easy

### Check that part starts and ends within subscription start and end (when saving the part)

- [ ] See also: #366. 

### at each time in the lifetime of a subscription at least one membership must be active

Or more exactly, whenever the subscription isn't empty (if that is changed, see other points).
Needs some more thought.

**Comment by motu55** [comment]
short info for the subscription reactivation
this is mostly a billing issue
for example a person deactivates there subscription after 2 years at the end of the busniess year, then after 6 month they want their subscription back.
ich te deactivation date would be removed the billing would assume the subscription was active the whole year and would bill for the whole year since there would be no information about the 6 months gap

**Comment by pascalfree** [comment]
Related to this topic the following issue came up:
- admin accidentially deactivated a subscription too early (today instead of at the end of the month).
- Deactivation can not be reverted, as activation of inactive sub is prohibited.
- Deactivation can not be moved to the future due to this validation https://github.com/juntagrico/juntagrico/blob/43a1d6743c53e64fca650ea732dcc692b2cba173/juntagrico/lifecycle/sub.py#L90 Probably because the reciepients doesn't feature the members that will have their date moved to the future. Anyways this is a violating a bit the reactivation prevention.
- https://github.com/juntagrico/juntagrico/issues/529 would fix this most likely.

In general at least a super admin should have a way to "reactivate" the subscription for such situations.

**Comment by pascalfree** [comment]
Another scenario:
A sub is created and admin wants to already set a deactivation date to indicate that the sub is of limited duration (trial sub). But they don't want to deactivate the full sub in the future yet as the sub might be extended. In that case a new part would be created on the same sub.
That is currently not possible as subs always must have an active part and deactivate subs can't be reactivated.

**Comment by pascalfree** [comment]
Note that there are changes in 4.1. The unique constraints are checked as part of model validation by default now: https://docs.djangoproject.com/en/4.1/ref/models/instances/#validating-objects

**Comment by pascalfree** [comment]
Shares canceled via admin form currently don't check if they are required for a subscription.
