### ISSUE TITLE
Use EMAIL_BACKEND instead of Mailer

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#605]
Django offers a way to select a backend for emails with the EMAIL_BACKEND setting. All emails are pass through this backend and the backend decides what to do with the email (e.g. send it via SMTP).
This can be used for the same purpose as our DEFAULT_MAILER setting https://github.com/juntagrico/juntagrico/blob/b82b44c1d60d263d6e765edf4165261a74892425/juntagrico/config.py#L115

The advantage of using the backend would be, that all django apps respect it (e.g. auth with the password reset process), without having to modify them individually.

The whitelisting and from filtering should also be applied in the backend instead of in the mailer because they should apply to other apps emails as well: https://github.com/juntagrico/juntagrico/blob/b82b44c1d60d263d6e765edf4165261a74892425/juntagrico/mailer/__init__.py#L94-L103

# Todo

- [ ] Use the EMAIL_BACKEND setting and create backend classes that replace the Mailer classes.
- [ ] Deprecate the DEFAULT_MAILER setting and Mailer classes.
- [ ] Move whitelisting and from_filtering to the backend class.
- [ ] Write upgrade instructions.
